// Phase 5.77 · 21.09.2026 17:08:17 CEST: Cache-/Request-Audit optimiert DAO-History-Sessioncache sowie TLN/VOW-Lazy-Loads für Team/LP-History/31.12.-Historie.
// Phase 5.58: Apertum-NFT-Kaufpreise prüfen nun ERC-20 sowie native APTM-Zahlungen in der Erwerbs-Tx und deren Internal Transactions. Alte negative Preisbefunde werden wegen Resolver-Version 2 einmalig neu ausgewertet. Reine Transfers/Mints werden nicht als fehlender Kaufpreis dargestellt.\n// Phase 5.58: Historische NFT-Entry-Txs werden auch bei noch offener Kaufprüfung erhalten. Kaufpreis-Negativbefunde gelten nur mit konkret geprüfter Erwerbs-Tx als abgeschlossen; alte unvollständige 5.56-Befunde werden automatisch erneut geprüft.\n// Phase 5.56: NFT-Daten werden bereits beim App-Start aus der zentralen Supabase-Registry geladen. Historische Kaufpreis-Evidenz wird am NFT persistent gecacht und von allen Verbrauchern gemeinsam genutzt; der NFT-Tab muss nicht zuerst geöffnet werden.
// Phase 5.55: DAO-Team verwendet für bekannte eigene DIDs die zentrale NFT-/Ownership-Zuordnung als autoritative DID→Wallet-Quelle. Historische Tree-Event-Wallets dürfen einen aktuellen Owner nicht überschreiben. Mehrere projektspezifische Uplines eines eigenen Wallets (DAO1/APTMDAO) werden parallel oberhalb des Einstiegsknotens angezeigt.
// Phase 5.54: DAO-Walletgraph ergänzt die Parent-Kante eigener Root-DIDs; verbundene eigene Wallets erscheinen dadurch wie im TLN-Baum untereinander. Botdetails kombinieren aktuellen Owner mit historischer Erwerbsevidenz statt First-Wins-Dedup. NFT-Adressen verwenden das transparente Standard-Copy-Icon; frühester on-chain Besitzzeitpunkt bleibt sichtbar.
// Phase 5.52: DAO-Team als ein gemeinsamer wallet-zentrierter Baum auch über mehrere eigene Wallets; eigene Wallets werden nach belegter DID-Upline eingehängt, aber nicht als Partner gezählt. DAO-Botdetails zeigen aktuellen Bestand getrennt von früheren/übertragenen Bots. NFT-Walletadressen verwenden das einheitliche Copy-Icon.
// Phase 5.51: Start-Dashboard nutzt denselben vollständigen Navigationszustand wie ein manueller Dashboard-Aufruf. NFT-Bestand zeigt zusätzlich Kauf/Mint-Wallet und aktuelles Wallet mit kopierbarer Adresse; Grundlage ist die gespeicherte Ownership-/Transferhistorie.
// Phase 5.50: DAO-Team Root-Erkennung cache-first stabilisiert: persistierte Ownership und NFT-Fallback berücksichtigen alle User-Wallets; aktuelle Projekt-Balances sind keine Voraussetzung mehr. Dashboard lädt Ownership vor den DAO-Tree-Caches.
// Phase 5.49: DAO-Team standardmäßig wallet-zentriert (1 Wallet = 1 Partner). Mehrere DIDs desselben Wallets werden visuell zusammengeführt, die DAO1-/APTMDAO-Graphen bleiben getrennt. Neue MinerBot-Käufe nutzen die im Kaufaufruf übergebene APTMDAO-DID für die Zweigzuordnung; eigene Wallets erscheinen nicht in Letzte Partneraktivitäten.
// Phase 5.48: Alte DAO1-Eigenbots bleiben über ihren historisch verifizierten ersten Besitzabschnitt einer DID zuordenbar, auch wenn die frühere Zahlungsstruktur keinen Kaufpreis erneut erkennen lässt. Fremde/live Bot-Transfers bleiben ohne Kaufnachweis unzugeordnet.
// Phase 5.47: Bei DAO1/APTMDAO wird ein Bot seiner DID anhand der historischen Besitzlage beim ursprünglichen Erwerb zugeordnet. Spätere unabhängige Transfers von Bot oder DID ändern die Zuordnung nicht; Identitäts-NFTs erscheinen nicht nochmals als Bot-Zeile.
// Phase 5.46: DAO1/APTMDAO-Bots werden anhand des historischen DID-Besitzes am Bot-Erwerbsblock zugeordnet. Heutiger Wallet-Besitz, Mint-Wallet oder gemeinsamer MineBot-Contract reichen nicht. Breite NFT-Wallet-Scans wurden aus den Teamdetails entfernt.
// Phase 5.45: DAO1/APTMDAO-Bots werden nicht mehr per gemeinsamer Besitzer-Wallet einem Tree zugeschlagen. Neue APTMDAO-Bots brauchen positiven Erwerbs-/Manager-Nachweis; alte DAO1-Bots behalten die bestehende Legacy-Erwerbs- und Kaufpreislogik.
// Phase 5.44: Hotfix: DAO1/APTMDAO-Teammodul lädt wieder vollständig; fehlende Tree-Modus-/Render-Funktionen aus dem 5.43-Umbau wurden wiederhergestellt.
// Phase 5.43: DAO-Team bleibt beim Rendern cache-only; Explorer-NFT/Tx-Abfragen erfolgen nur gezielt in Partnerdetails, werden dedupliziert und begrenzt. Neue Bots eigener Roots werden dort live ergänzt; DID-NFTs selbst erscheinen nie als Bots.
// Phase 5.42: Dashboard-Kurse: Token ohne Icon, Chain mit Native-Symbol, bekannte Tokenstammdaten vor Contract-Fallback; DAO-DID/Bot-Trennung und LP-frei/gebunden fachlich geschärft.
// Phase 5.41: Dashboard-Werte auditierbar aufgesplittet; LP-Staking ohne Doppelzählung; DAO1/APTMDAO Partner-Bots nur bei eindeutiger Tree-Evidenz; Partner-Bot-Lifecycle persistent; Preis-Freshness je Asset.
// Phase 5.75: Request-Audit im Admin-Systemtab; Seiten-Reload startet strikt kein loadAll(). TLN/VOW wird nicht für eine Dashboard-Summary initialisiert. NFT-Current-State bleibt Startcache, historische Ersterwerbs-/Kaufpreis-Aufbereitung beginnt erst im NFT-Tab.
// Cache-first Start ab 18.09.2026: Seiten-Reload zeigt gespeicherte Daten und startet keine grossen Balance/NFT/Projekt-On-Chain-Jobs automatisch. Projektmodule wie DAO1 laden Detail-Caches lazy beim Öffnen.
(() => {
// WalletTracking · Allgemeine Hilfe
// Eigenständiges Hilfe-Modul. Künftige Inhaltsänderungen sollen möglichst nur hier erfolgen.
const HELP_MODULE_BUILD="20260921-162541";
const HELP_MODULE_TIMESTAMP="19.09.2026 01:36:47 CEST";
function renderGeneralHelp(){
  const el=document.getElementById("generalHelpContent");
  if(!el)return;
  el.innerHTML=`<div class="section-title">❓ Hilfe / Handbuch</div>

      <div class="custom-token-card">
        <h3 style="margin-top:0">Schnellstart</h3>
        <p class="note"><strong>1.</strong> Neue User starten mit einem leeren Dashboard und können dort direkt „Erste Wallet erfassen“ wählen. Unter „Meine Wallets“ jede Wallet als „Eigenes Wallet“ markieren oder einem Besitzer zuordnen. <strong>2.</strong> Das Dashboard ist die Startseite und zeigt sofort den gespeicherten Stand für den gewählten Personenfilter. <strong>3.</strong> „Daten aktualisieren“ erneuert Bestände und projektübergreifende Daten. <strong>4.</strong> „Preise aktualisieren“ erneuert davon getrennt die aktuellen Kurse und USD-Werte. <strong>5.</strong> Unbekannte Token bei Bedarf unter „Entdecken“ prüfen und als eigene sichere Token übernehmen. Für Projektdetails das jeweilige DeFi-Projekt öffnen.</p>
      </div>

      <div class="custom-token-card"><h3 style="margin-top:0">🔤 Darstellung</h3><p class="note">Die Hauptnavigation befindet sich als klar gegliederte Seitenleiste links; auf schmalen Displays ordnet sie sich responsiv oberhalb des Inhalts an. Chain- und Token-Identitäten werden in Datentabellen mit kompakten Symbolen unterstützt. Die Schriftgrösse der gesamten Anwendung kann oben im Kopfbereich mit dem Regler „Schrift“ individuell von 85 % bis 125 % eingestellt werden. Die Einstellung wird auf diesem Gerät gespeichert. Farben, Cards, Navigation, Tabs und Tabellen werden zentral über <code>css/wallet-tracking.css</code> gesteuert.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">📊 Dashboard, Wallet-Ansicht &amp; Aktualisierung</h3><p class="note">Das Dashboard ist die Startseite. Der zentrale Filter „Wallet-Ansicht“ zeigt Wallets aller Personen, nur eigene Wallets oder die Wallets einer bestimmten erfassten Person. Dieser Filter verändert nur die Darstellung; Discovery- und Aktualisierungslogik werden dadurch nicht fachlich eingeschränkt. Beim Login wird das Dashboard sofort aus gespeicherten Beständen, dem globalen aktuellen Preis-Snapshot und kleinen Projekt-Summaries dargestellt. Aktuelle Preise werden global – nicht pro User – höchstens einmal je 15-Minuten-Slot (xx:00/15/30/45) nachgeführt, solange mindestens ein User aktiv ist; alle User lesen danach denselben Snapshot. Historische Preise werden dadurch nicht gespeichert. Projekt-Grunddaten dürfen cache-first im Hintergrund nachgeführt werden, ohne den vollständigen Projekt-Tab oder eine Voll-Discovery zu starten. Manuelle Snapshots, allgemeiner Discovery-Cache, Gebühren-Summary und vollständige Projekt-Discovery bleiben bereichs-/manuell gesteuert. „Daten aktualisieren“ und „Preise aktualisieren“ bleiben zusätzlich als bewusste manuelle Aktionen verfügbar.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🧮 Dashboard-Kennzahlen</h3><p class="note"><strong>Standardmäßig zählen nur eigene Wallets.</strong> Als verwaltet beziehungsweise fremd markierte Wallets werden erst über „Wallets aller Personen“ oder die konkrete Person einbezogen. <strong>Gesamtvermögen</strong> ist die Summe aller mit einem gespeicherten Kurs bewertbaren freien und gebundenen Bestände im gewählten Bereich. <strong>Frei verfügbar</strong> ist der bewertbare Anteil, der laut vorhandenem Stand nicht als gestakt oder anderweitig gebunden ausgewiesen ist. <strong>Aktuell gebunden</strong> wird nur aus einem bereits vorhandenen, belegten Positionscache berechnet. Projekt-Kacheln zeigen den bewertbaren Projektwert zusätzlich als frei verfügbar, aktuell gebunden und gesamt. Eine LP-Position wird dabei nicht nochmals aus dem Positionscache addiert, wenn derselbe gestakte Anteil bereits im Wallet-/Projektbestand integriert ist. <strong>Rewards</strong> und <strong>Referral Rewards</strong> werden im Dashboard strikt getrennt und jeweils für Gesamt, Vorjahr, laufendes Jahr und laufenden Monat ausgewiesen. Projekt-Summen müssen dieselben fachlichen Regeln wie die jeweiligen Detailtabs verwenden. Reward-Summaries werden nicht in USD umgerechnet, sondern je Originaltoken/-währung ausgewiesen. TLN/VOW führt Staking-Rewards, Referral Rewards und Bonus-Rewards getrennt.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🎁 Dashboard-Rewards</h3><p class="note">Rewards und Referral Rewards werden im Dashboard bewusst in der tatsächlich ausgezahlten Währung bzw. im Originaltoken zusammengefasst. Es erfolgt dort keine USD-Umrechnung. Gleichnamige Assets werden intern über Chain + Contract/Asset-ID getrennt. DAO1- und APTMDAO-Partner werden getrennt ausgewiesen und weder addiert noch dedupliziert, weil beide DAO-Versionen eigene DIDs und auch unterschiedliche Wallets derselben Person verwenden können. Partner-Bots werden historisch zum Bot-Erwerbsblock zugeordnet: WalletTracking prüft, welche DAO1-/APTMDAO-DID zu genau diesem Zeitpunkt auf derselben Wallet lag. Bot und DID können unabhängig verschoben werden; heutiger Besitz oder die ursprüngliche Mint-Wallet sind daher kein Beweis. Liegt zum Erwerbszeitpunkt genau eine APTMDAO-DID auf der Wallet, gehört der Bot zum neuen Tree; sonst kann genau eine alte DAO1-DID zugeordnet werden. Mehrdeutige Fälle bleiben bewusst unzugeordnet.</p></div><div class="custom-token-card"><h3 style="margin-top:0">💾 Cache &amp; Datenstand</h3><p class="note">WalletTracking arbeitet bewusst mit persistenten Caches, damit bereits bekannte Blockchain-Historien nicht bei jedem Öffnen vollständig neu geladen werden. Fachlich unveränderliche Historie wird inkrementell ergänzt. Daten, deren Zustand sich später ändern kann, müssen trotz Cache erneut geprüft werden. Eine gültige Cache-Version bedeutet deshalb nicht automatisch, dass ein veränderlicher On-Chain-Status für immer aktuell bleibt.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">💰 Kurse</h3><p class="note">Aktuelle Kurse werden global in einem einzigen Snapshot gehalten und bei aktiver Anwendung höchstens einmal pro 15-Minuten-Slot aktualisiert; „Preise aktualisieren“ kann zusätzlich manuell aktualisieren. Token mit einem bewertbaren Bestand von mehr als 1 USD werden automatisch in der Kursliste gezeigt. Das Token-Flag heißt „Im Dashboard immer anzeigen“ und hält den Kurs auch bei Bestand 0 sichtbar. Projektgebundene Token erscheinen nur, wenn für den User eine Beteiligung am betreffenden Projekt aus Bestand oder bestätigtem Projekt-Summary belegt ist. Anzeige-Kommastellen sind von den technischen Token-Decimalseinstellungen getrennt. Für Summaries gilt: leeres Feld = Anzeige-Kommastellen übernehmen; 0 = wirklich ohne Nachkommastellen. Neu geladene Einzelpreise tragen zusätzlich ihren eigenen Refresh-Zeitpunkt; ein bei Teilfehlern beibehaltener alter Kurs wird dadurch nicht als frisch erneuert behandelt. Historische Bewertungen verwenden weiterhin ihre eigene historische Preislogik.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🧾 Bestandesaufnahme per 31.12.</h3><p class="note">Wähle Stichtag, Zeitzone und eine Wallet oder „Alle Wallets“. „Neu berechnen“ ermittelt den historischen Bestand und speichert den verifizierten Jahresstand dauerhaft. „Nur Kurse aktualisieren“ verändert bereits bestätigte Bestandsmengen nicht. Positionen ohne historischen Kurs bleiben sichtbar und werden nicht stillschweigend aus der Historie entfernt. PDF-/Excel-Exporte dokumentieren die verfügbaren Werte und Quellen.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">💸 Gebühren · 🖼️ NFTs · 🔓 Freigaben</h3><p class="note"><strong>Gebühren:</strong> werden walletbezogen gespeichert und gezielt aktualisiert. <strong>NFTs:</strong> werden über die vorgesehenen Wallet-/Projektjobs geladen; Spam-/Sicher-Klassifikationen bleiben getrennt von der eigentlichen On-Chain-Erkennung. <strong>Freigaben:</strong> zeigen Token-Approvals rein lesend an; ein Widerruf erfolgt extern mit der eigenen Wallet.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">⚙️ Verwaltung</h3><p class="note"><strong>Meine Wallets:</strong> eigene Wallets verwalten. <strong>Vordefinierte Token:</strong> normale Benutzer sehen die freigegebenen Stammdaten nur lesend; Bearbeitung und technische Verwaltungsfelder sind Admin-Funktionen. <strong>Eigene sichere Token:</strong> persönliche Ergänzungen. <strong>Entdecken:</strong> durchsucht bei Bedarf auch historische Aktivitäten nach früher gehaltenen Token/Positionen.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🔐 Datenschutz</h3><p class="note">Private Scan-/LP-Caches referenzieren eigene Wallets ausschließlich über die usergebundene wallet_id; eigene Wallet-Adressen werden dort nicht zusätzlich persistent gespeichert. RLS-Schutzregeln verhindern ein versehentliches Wiedereintragen von Klartextadressen. Private Walletdaten, Wallet-Besitzernamen und persönliche Partner-Aliase werden userbezogen verschlüsselt gespeichert. Der Besitzername wird ausschließlich über die geschützte Wallet-Edge-Function gelesen und geschrieben. Öffentliche Blockchain-Daten bleiben naturgemäß öffentlich. Private Namen/Zuordnungen gehören nicht in globale oder öffentliche Caches.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">📋 Chain-Abdeckung</h3><p class="note">Die Tabelle zeigt, welche allgemeinen Funktionen pro Chain technisch vorgesehen sind. Die konkrete Abdeckung eines einzelnen Laufs kann davon abweichen und wird beim jeweiligen Ergebnis ausgewiesen.</p><div id="helpChainCoverage"></div></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🏦 Projekte</h3><p class="note"><strong>Projektspezifische Bedienung und Fachlogik gehören nicht in dieses allgemeine Handbuch.</strong> Der Hauptpunkt „DeFi-Projekte“ öffnet zuerst eine neutrale Übersicht und lädt dabei bewusst noch keine projektspezifischen Daten. Öffne danach TLN/VOW, DAO1 oder ein anderes DeFi-Projekt und dort den eigenen Unter-Tab „Hilfe“. Dort werden projektspezifische Tabs, Datenquellen, Cache-/Refresh-Regeln, Statusmodelle und Besonderheiten dokumentiert.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">⚡ Cache- &amp; Ladeprinzip</h3><p class="note">WalletTracking arbeitet cache-first: vorhandene bestätigte Daten werden sofort angezeigt. Ein Seitenreload startet keinen breiten <code>loadAll()</code>-On-Chain-Lauf mehr; eine fällige Aktualisierung wird angezeigt und bewusst ausgelöst. Große globale Datenbestände sollen innerhalb eines App-Laufs gemeinsam wiederverwendet werden. Aktuelle Bestände (Wallet/NFT/Bot/Position) bleiben technisch von historischen Kaufpreis-, Lifecycle- und DID-Zuordnungen getrennt. Deshalb lädt die zentrale NFT-Registry beim Start den Current State, während globale Ersterwerbs- und Kaufpreis-Historie erst beim NFT-Tab nachläuft. Im Admin-Systemtab zeigt der Request-Audit Supabase-/RPC-/API-Signaturen, Scope/Filter, Anzahl und Laufzeiten des aktuellen Browser-Tabs.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">💬 Support</h3><p class="note">Wenn Daten fehlen oder eine Abfrage fehlschlägt, sende möglichst Projekt/Chain, Wallet-Bezeichnung, betroffene Funktion sowie die sichtbare Fehlermeldung oder Tx. Private Keys und Seed-Phrases gehören niemals in den Chat.</p></div>`;
}
window.renderGeneralHelp=renderGeneralHelp;
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>renderGeneralHelp(),{once:true});
else renderGeneralHelp();
})();

// Phase 5.54: DAO-NFT-Daten folgen einer zentralen Single-Source-of-Truth. Ansichten lösen Ownership/Kaufhistorie nicht parallel neu auf, sondern verwenden den persistierten NFT-/Ownership-Bestand.

// Phase 5.74 · 21.09.2026 13:48:40 CEST: Nächster Entwicklungsfokus ist ein zentraler Cache-/Request-Audit. App-Start bleibt cache-first; identische parallele Supabase-/RPC-Abfragen sollen über In-Flight-Reuse zusammengeführt, große globale Datenbestände pro Session nur einmal geladen und Delta-Scans über DATA_VERSIONS/Scope/rootsKey/Cursor/Overlap gesteuert werden. Current State darf nicht auf historische Kaufpreis-/Lifecycle-/DID-Aufbereitung warten. Build 20260921-134840.

// Phase 5.75 · 21.09.2026 14:13:07 CEST: Zentraler Session-Request-Audit aktiv; kein automatisches loadAll() beim Login; TLN/VOW-Dashboard startet keine Discovery-Initialisierung; NFT-History erst im NFT-Tab. Build 20260921-170817.

// Phase 5.76 · 21.09.2026 16:25:41 CEST: Request-Audit/Systemübersicht-Hotfix. cache_data_versions wird im Systemtab in-flight dedupliziert und kurz wiederverwendet; DAO-Team-Versionen werden vor dem UI-Status zusammengeführt, damit kein rekursiver Requestloop entsteht. Build 20260921-162541.
