// Cache-first Start ab 18.09.2026: Seiten-Reload zeigt gespeicherte Daten und startet keine grossen Balance/NFT/Projekt-On-Chain-Jobs automatisch. Projektmodule wie DAO1 laden Detail-Caches lazy beim Öffnen.
(() => {
// WalletTracking · Allgemeine Hilfe
// Eigenständiges Hilfe-Modul. Künftige Inhaltsänderungen sollen möglichst nur hier erfolgen.
const HELP_MODULE_BUILD="20260919-120422";
const HELP_MODULE_TIMESTAMP="19.09.2026 12:04:22 CEST";
function renderGeneralHelp(){
  const el=document.getElementById("generalHelpContent");
  if(!el)return;
  el.innerHTML=`<div class="section-title">❓ Hilfe / Handbuch</div>

      <div class="custom-token-card">
        <h3 style="margin-top:0">Schnellstart</h3>
        <p class="note"><strong>1.</strong> Unter „Meine Wallets“ jede Wallet als „Eigenes Wallet“ markieren oder einem Besitzer zuordnen. <strong>2.</strong> Das Dashboard ist die Startseite und zeigt sofort den gespeicherten Stand für den gewählten Personenfilter. <strong>3.</strong> „Daten aktualisieren“ erneuert Bestände und projektübergreifende Daten. <strong>4.</strong> „Preise aktualisieren“ erneuert davon getrennt die aktuellen Kurse und USD-Werte. <strong>5.</strong> Unbekannte Token bei Bedarf unter „Entdecken“ prüfen und als eigene sichere Token übernehmen. Für Projektdetails das jeweilige DeFi-Projekt öffnen.</p>
      </div>

      <div class="custom-token-card"><h3 style="margin-top:0">🔤 Darstellung</h3><p class="note">Die Hauptnavigation befindet sich als klar gegliederte Seitenleiste links; auf schmalen Displays ordnet sie sich responsiv oberhalb des Inhalts an. Chain- und Token-Identitäten werden in Datentabellen mit kompakten Symbolen unterstützt. Die Schriftgrösse der gesamten Anwendung kann oben im Kopfbereich mit dem Regler „Schrift“ individuell von 85 % bis 125 % eingestellt werden. Die Einstellung wird auf diesem Gerät gespeichert. Farben, Cards, Navigation, Tabs und Tabellen werden zentral über <code>css/wallet-tracking.css</code> gesteuert.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">📊 Dashboard, Wallet-Ansicht &amp; Aktualisierung</h3><p class="note">Das Dashboard ist die Startseite. Der zentrale Filter „Wallet-Ansicht“ zeigt Wallets aller Personen, nur eigene Wallets oder die Wallets einer bestimmten erfassten Person. Dieser Filter verändert nur die Darstellung; Discovery- und Aktualisierungslogik werden dadurch nicht fachlich eingeschränkt. Beim Login werden Bestände und Kurse ausschließlich aus dem gespeicherten Stand dargestellt. Ein fehlender oder älterer Preis-Cache startet keine Preis-API, keinen Pool-RPC und keine Projekt-Discovery. Manuelle Snapshots, allgemeiner Discovery-Cache, Gebühren-Summary, NFT-Cache und TLN/VOW-Discovery werden erst beim Öffnen ihres Bereichs geladen. „Daten aktualisieren“ beziehungsweise „Preise aktualisieren“ bleiben bewusste manuelle Aktionen.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🧮 Dashboard-Kennzahlen</h3><p class="note"><strong>Standardmäßig zählen nur eigene Wallets.</strong> Als verwaltet beziehungsweise fremd markierte Wallets werden erst über „Wallets aller Personen“ oder die konkrete Person einbezogen. <strong>Projektkarten:</strong> Projekte und Administration sind getrennte Bereiche. Je Projekt sind Teampartner gesamt/aktiv sowie Rewards Gesamt/Vorjahr/Jahr/Monat vorgesehen; diese Werte werden ausschließlich aus vorhandenen Projektcaches übernommen und starten keine Discovery. <strong>Gesamtvermögen</strong> ist die Summe aller mit einem gespeicherten Kurs bewertbaren freien und gebundenen Bestände im gewählten Bereich. <strong>Frei verfügbar</strong> ist der bewertbare Anteil, der laut vorhandenem Stand nicht als gestakt oder anderweitig gebunden ausgewiesen ist. <strong>Aktuell gebunden</strong> wird nur aus einem bereits vorhandenen, belegten Positionscache berechnet; fehlt dieser Nachweis, zeigt das Dashboard bewusst „–“ statt einer geschätzten Null. Unbewertete Token werden sichtbar gemeldet und nicht still in die Geldsumme eingerechnet.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">💾 Cache &amp; Datenstand</h3><p class="note">WalletTracking arbeitet bewusst mit persistenten Caches, damit bereits bekannte Blockchain-Historien nicht bei jedem Öffnen vollständig neu geladen werden. Fachlich unveränderliche Historie wird inkrementell ergänzt. Daten, deren Zustand sich später ändern kann, müssen trotz Cache erneut geprüft werden. Eine gültige Cache-Version bedeutet deshalb nicht automatisch, dass ein veränderlicher On-Chain-Status für immer aktuell bleibt.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">💰 Kurse</h3><p class="note">Die aktuelle Kursaktualisierung wird zentral über „Preise aktualisieren“ gesteuert. Administratoren wählen in der Token-Tabelle über „Im Dashboard anzeigen“, welche Tokenkurse auf dem Dashboard erscheinen. Das gilt auch für native Coins; sie werden als zentrale Stammdaten geführt und besitzen eigene Anzeige-/Summary-Kommastellen. Im Dashboard wird der gepflegte Token-Name angezeigt; Contract-Adressen erscheinen nur verkürzt mit Kopierfunktion. Bei Projektkursen werden die tatsächliche DEX-Quelle und – soweit vorhanden – die bereits ermittelte Preisroute angezeigt. DAO1 besitzt dafür einen eigenen Tab „Kurse und Pools“, der ausschließlich die bestehende Apertum-Preislogik und deren gespeicherte Ergebnisse sichtbar macht und keine neue Preisermittlung startet. Projektkurse werden nur zusammen mit einer tatsächlich vorhandenen Projekt-Kachel gezeigt. Anzeige-Kommastellen sind von den technischen Token-Decimalseinstellungen getrennt. Historische Bewertungen verwenden weiterhin ihre eigene historische Preislogik.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🧾 Bestandesaufnahme per 31.12.</h3><p class="note">Wähle Stichtag, Zeitzone und eine Wallet oder „Alle Wallets“. „Neu berechnen“ ermittelt den historischen Bestand und speichert den verifizierten Jahresstand dauerhaft. „Nur Kurse aktualisieren“ verändert bereits bestätigte Bestandsmengen nicht. Positionen ohne historischen Kurs bleiben sichtbar und werden nicht stillschweigend aus der Historie entfernt. PDF-/Excel-Exporte dokumentieren die verfügbaren Werte und Quellen.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">💸 Gebühren · 🖼️ NFTs · 🔓 Freigaben</h3><p class="note"><strong>Gebühren:</strong> werden walletbezogen gespeichert und gezielt aktualisiert. <strong>NFTs:</strong> werden über die vorgesehenen Wallet-/Projektjobs geladen; Spam-/Sicher-Klassifikationen bleiben getrennt von der eigentlichen On-Chain-Erkennung. <strong>Freigaben:</strong> zeigen Token-Approvals rein lesend an; ein Widerruf erfolgt extern mit der eigenen Wallet.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">⚙️ Verwaltung</h3><p class="note"><strong>Meine Wallets:</strong> eigene Wallets verwalten. <strong>Vordefinierte Token:</strong> normale Benutzer sehen die freigegebenen Stammdaten nur lesend; Bearbeitung und technische Verwaltungsfelder sind Admin-Funktionen. <strong>Eigene sichere Token:</strong> persönliche Ergänzungen. <strong>Entdecken:</strong> durchsucht bei Bedarf auch historische Aktivitäten nach früher gehaltenen Token/Positionen.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🔐 Datenschutz</h3><p class="note">Private Walletdaten, Wallet-Besitzernamen und persönliche Partner-Aliase werden userbezogen verschlüsselt gespeichert. Der Besitzername wird ausschließlich über die geschützte Wallet-Edge-Function gelesen und geschrieben. Öffentliche Blockchain-Daten bleiben naturgemäß öffentlich. Private Namen/Zuordnungen gehören nicht in globale oder öffentliche Caches.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">📋 Chain-Abdeckung</h3><p class="note">Die Tabelle zeigt, welche allgemeinen Funktionen pro Chain technisch vorgesehen sind. Die konkrete Abdeckung eines einzelnen Laufs kann davon abweichen und wird beim jeweiligen Ergebnis ausgewiesen.</p><div id="helpChainCoverage"></div></div>

      <div class="custom-token-card"><h3 style="margin-top:0">🏦 Projekte</h3><p class="note"><strong>Projektspezifische Bedienung und Fachlogik gehören nicht in dieses allgemeine Handbuch.</strong> Der Hauptpunkt „DeFi-Projekte“ öffnet zuerst eine neutrale Übersicht und lädt dabei bewusst noch keine projektspezifischen Daten. Öffne danach TLN/VOW, DAO1 oder ein anderes DeFi-Projekt und dort den eigenen Unter-Tab „Hilfe“. Dort werden projektspezifische Tabs, Datenquellen, Cache-/Refresh-Regeln, Statusmodelle und Besonderheiten dokumentiert.</p></div>

      <div class="custom-token-card"><h3 style="margin-top:0">💬 Support</h3><p class="note">Wenn Daten fehlen oder eine Abfrage fehlschlägt, sende möglichst Projekt/Chain, Wallet-Bezeichnung, betroffene Funktion sowie die sichtbare Fehlermeldung oder Tx. Private Keys und Seed-Phrases gehören niemals in den Chat.</p></div>`;
}
window.renderGeneralHelp=renderGeneralHelp;
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>renderGeneralHelp(),{once:true});
else renderGeneralHelp();
})();
