window.WalletLPEngine = (() => {
  const V2 = new ethers.Interface([
    "function token0() view returns(address)","function token1() view returns(address)",
    "function getReserves() view returns(uint112,uint112,uint32)","function totalSupply() view returns(uint256)",
    "function balanceOf(address) view returns(uint256)","function decimals() view returns(uint8)","function factory() view returns(address)"
  ]);
  const ERC20 = new ethers.Interface(["function symbol() view returns(string)","function name() view returns(string)","function decimals() view returns(uint8)"]);
  let ctx=()=>({}); const pairCache=new Map(), metaCache=new Map();
  const norm=x=>String(x||"").toLowerCase();
  const hex=n=>"0x"+Number(n).toString(16);
  async function rpc(chain,method,params=[]){const c=ctx(),url=c.chainConfig?.[chain]?.archiveRpcUrl||c.chainConfig?.[chain]?.rpcUrl;if(!url)throw new Error(`${chain}: RPC fehlt`);const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:Date.now(),method,params})});if(!r.ok)throw new Error(`${chain}: RPC HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error.message||"RPC Fehler");return j.result;}
  async function call(chain,to,data,block="latest"){return rpc(chain,"eth_call",[{to,data},block==="latest"?"latest":hex(block)]);}
  async function meta(chain,address){const k=chain+"|"+norm(address);if(metaCache.has(k))return metaCache.get(k);const c=ctx(),pk=k;let m={address,symbol:c.predefinedTokenSymbols?.[pk]||null,name:c.predefinedTokenNames?.[pk]||null,decimals:c.predefinedTokenDecimals?.[pk]};try{if(!m.symbol)m.symbol=ERC20.decodeFunctionResult("symbol",await call(chain,address,ERC20.encodeFunctionData("symbol",[])))[0];}catch{}try{if(!Number.isFinite(Number(m.decimals)))m.decimals=Number(ERC20.decodeFunctionResult("decimals",await call(chain,address,ERC20.encodeFunctionData("decimals",[])))[0]);}catch{}m.decimals=Number.isFinite(Number(m.decimals))?Number(m.decimals):18;m.symbol=m.symbol||address.slice(0,8)+"…";metaCache.set(k,m);return m;}
  async function pairInfo(chain,address,block="latest"){const key=chain+"|"+norm(address)+"@"+block;if(pairCache.has(key))return pairCache.get(key);try{const [t0r,t1r,rr,tsr,dr,fr]=await Promise.all([call(chain,address,V2.encodeFunctionData("token0",[]),block),call(chain,address,V2.encodeFunctionData("token1",[]),block),call(chain,address,V2.encodeFunctionData("getReserves",[]),block),call(chain,address,V2.encodeFunctionData("totalSupply",[]),block),call(chain,address,V2.encodeFunctionData("decimals",[]),block),call(chain,address,V2.encodeFunctionData("factory",[]),block)]);const [t0]=V2.decodeFunctionResult("token0",t0r),[t1]=V2.decodeFunctionResult("token1",t1r),[r0,r1]=V2.decodeFunctionResult("getReserves",rr),[supply]=V2.decodeFunctionResult("totalSupply",tsr),[dec]=V2.decodeFunctionResult("decimals",dr),[factory]=V2.decodeFunctionResult("factory",fr);if(!t0||!t1||norm(t0)===norm(t1))return null;const [m0,m1]=await Promise.all([meta(chain,t0),meta(chain,t1)]);const out={chain,address:norm(address),factory:norm(factory),decimals:Number(dec),total:Number(ethers.formatUnits(supply,Number(dec))),t0:m0,t1:m1,r0:Number(ethers.formatUnits(r0,m0.decimals)),r1:Number(ethers.formatUnits(r1,m1.decimals))};pairCache.set(key,out);return out;}catch{return null;}}
  function label(chain){return chain==="bsc"?"PCLP":chain==="apertum"?"DAO1-LP":"LP";}
  async function balance(chain,pair,wallet,block="latest"){const raw=await call(chain,pair.address,V2.encodeFunctionData("balanceOf",[wallet]),block);const [b]=V2.decodeFunctionResult("balanceOf",raw);return Number(ethers.formatUnits(b,pair.decimals));}
  async function valuePosition(chain,pair,bal,block="latest",dateStr=null){const share=pair.total>0?bal/pair.total:0,a0=pair.r0*share,a1=pair.r1*share,c=ctx();let p0=null,p1=null;if(c.historicalPrice){p0=await c.historicalPrice(chain,{address:pair.t0.address,symbol:pair.t0.symbol,decimals:pair.t0.decimals},dateStr,block).catch(()=>null);p1=await c.historicalPrice(chain,{address:pair.t1.address,symbol:pair.t1.symbol,decimals:pair.t1.decimals},dateStr,block).catch(()=>null);}else if(c.currentPrice){p0=c.currentPrice(chain,pair.t0.address);p1=c.currentPrice(chain,pair.t1.address);}const usd=(p0?.price!=null&&p1?.price!=null)?a0*p0.price+a1*p1.price:null;return {balance:bal,share,amount0:a0,amount1:a1,price0:p0?.price??null,price1:p1?.price??null,usd};}
  async function positions(chain,wallet,candidates,block="latest",dateStr=null){const out=[];for(const a of [...new Set((candidates||[]).map(norm))]){const p=await pairInfo(chain,a,block);if(!p)continue;const b=await balance(chain,p,wallet,block).catch(()=>0);if(!(b>0))continue;out.push({...p,...await valuePosition(chain,p,b,block,dateStr),lpLabel:label(chain)});}return out;}
  function configure(fn){ctx=fn||ctx;}
  return {configure,pairInfo,positions,label,meta};
})();
