-- Wallet Tracking · DAO1/Apertum · Miner NFT ownership history · Phase 2
-- Run once in Supabase SQL Editor after 001-dao1-apertum.sql.

create table if not exists public.project_miner_ownership (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null default 'dao1',
  chain_key text not null default 'apertum',
  nft_contract text not null,
  nft_id bigint not null,
  wallet_address text not null,
  owned_from_block bigint,
  owned_to_block bigint,
  owned_from_at timestamptz,
  owned_to_at timestamptz,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists project_miner_ownership_lookup_idx
on public.project_miner_ownership
(user_id, project_key, wallet_address, nft_contract, nft_id);

create index if not exists project_miner_ownership_nft_idx
on public.project_miner_ownership
(user_id, project_key, nft_contract, nft_id, owned_from_block);

alter table public.project_miner_ownership enable row level security;

drop policy if exists project_miner_ownership_select_own on public.project_miner_ownership;
create policy project_miner_ownership_select_own on public.project_miner_ownership
for select to authenticated using (auth.uid() = user_id);

drop policy if exists project_miner_ownership_insert_own on public.project_miner_ownership;
create policy project_miner_ownership_insert_own on public.project_miner_ownership
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists project_miner_ownership_update_own on public.project_miner_ownership;
create policy project_miner_ownership_update_own on public.project_miner_ownership
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists project_miner_ownership_delete_own on public.project_miner_ownership;
create policy project_miner_ownership_delete_own on public.project_miner_ownership
for delete to authenticated using (auth.uid() = user_id);
