-- Wallet Tracking · Projekt-NFTs + generische Besitzhistorie · Phase 2d
-- Einmal im Supabase SQL Editor ausführen.

-- 1) Projektweite NFT-Klassifizierung: Was IST eine NFT?
create table if not exists public.project_nfts (
  id bigint generated by default as identity primary key,
  project_key text not null references public.defi_projects(project_key) on delete cascade,
  chain_key text not null,
  nft_contract text not null,
  nft_id bigint not null,
  nft_name text,
  category text,
  subtype text,
  notes text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_key, chain_key, nft_contract, nft_id)
);

create index if not exists project_nfts_project_idx
on public.project_nfts(project_key, chain_key, subtype, enabled);

alter table public.project_nfts enable row level security;

drop policy if exists project_nfts_read on public.project_nfts;
create policy project_nfts_read on public.project_nfts
for select to authenticated using (true);

drop policy if exists project_nfts_admin_insert on public.project_nfts;
create policy project_nfts_admin_insert on public.project_nfts
for insert to authenticated
with check (exists (select 1 from public.admins a where a.email = auth.jwt()->>'email'));

drop policy if exists project_nfts_admin_update on public.project_nfts;
create policy project_nfts_admin_update on public.project_nfts
for update to authenticated
using (exists (select 1 from public.admins a where a.email = auth.jwt()->>'email'))
with check (exists (select 1 from public.admins a where a.email = auth.jwt()->>'email'));

drop policy if exists project_nfts_admin_delete on public.project_nfts;
create policy project_nfts_admin_delete on public.project_nfts
for delete to authenticated
using (exists (select 1 from public.admins a where a.email = auth.jwt()->>'email'));

-- 2) Generische Besitzhistorie: Wem gehörte welche Projekt-NFT wann?
create table if not exists public.project_nft_ownership (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null default 'dao1',
  chain_key text not null default 'apertum',
  nft_contract text not null,
  nft_id bigint not null,
  nft_name text,
  wallet_address text not null,
  owned_from_block bigint,
  owned_to_block bigint,
  owned_from_at timestamptz,
  owned_to_at timestamptz,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists project_nft_ownership_wallet_idx
on public.project_nft_ownership(user_id, project_key, wallet_address, nft_contract, nft_id);

create index if not exists project_nft_ownership_nft_idx
on public.project_nft_ownership(user_id, project_key, nft_contract, nft_id, owned_from_block);

alter table public.project_nft_ownership enable row level security;

drop policy if exists project_nft_ownership_select_own on public.project_nft_ownership;
create policy project_nft_ownership_select_own on public.project_nft_ownership
for select to authenticated using (auth.uid() = user_id);

drop policy if exists project_nft_ownership_insert_own on public.project_nft_ownership;
create policy project_nft_ownership_insert_own on public.project_nft_ownership
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists project_nft_ownership_update_own on public.project_nft_ownership;
create policy project_nft_ownership_update_own on public.project_nft_ownership
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists project_nft_ownership_delete_own on public.project_nft_ownership;
create policy project_nft_ownership_delete_own on public.project_nft_ownership
for delete to authenticated using (auth.uid() = user_id);

-- 3) Bereits ermittelte DAO1-Besitzhistorie übernehmen.
insert into public.project_nft_ownership
(user_id,project_key,chain_key,nft_contract,nft_id,nft_name,wallet_address,
 owned_from_block,owned_to_block,owned_from_at,owned_to_at,is_current,created_at)
select
  user_id,project_key,chain_key,nft_contract,nft_id,nft_name,wallet_address,
  owned_from_block,owned_to_block,owned_from_at,owned_to_at,is_current,created_at
from public.project_miner_ownership old
where not exists (
  select 1 from public.project_nft_ownership n
  where n.user_id=old.user_id
    and n.project_key=old.project_key
    and n.nft_contract=old.nft_contract
    and n.nft_id=old.nft_id
    and n.wallet_address=old.wallet_address
    and coalesce(n.owned_from_block,-1)=coalesce(old.owned_from_block,-1)
);

-- Alte Tabellen bleiben vorerst bestehen, damit ein Rollback möglich ist.
