-- Wallet Tracking · DAO1/Apertum · inkrementeller Claim-Cache · Phase 2g
-- EINMAL im Supabase SQL Editor ausführen, nachdem 004 erfolgreich ausgeführt wurde.

-- Letzter erfolgreicher Scanstand je Wallet / Scan-Typ.
create table if not exists public.project_scan_state (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null,
  chain_key text not null,
  wallet_address text not null,
  scan_type text not null,
  last_scanned_block bigint not null default 0,
  last_scanned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, project_key, chain_key, wallet_address, scan_type)
);

create index if not exists project_scan_state_lookup_idx
on public.project_scan_state(user_id, project_key, chain_key, wallet_address, scan_type);

alter table public.project_scan_state enable row level security;

drop policy if exists project_scan_state_select_own on public.project_scan_state;
create policy project_scan_state_select_own on public.project_scan_state
for select to authenticated using (auth.uid() = user_id);

drop policy if exists project_scan_state_insert_own on public.project_scan_state;
create policy project_scan_state_insert_own on public.project_scan_state
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists project_scan_state_update_own on public.project_scan_state;
create policy project_scan_state_update_own on public.project_scan_state
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- Dauerhafter Claim-Cache. Eine Wallet-Historie wird nur beim ersten Mal vollständig
-- gelesen. Folge-Scans beginnen bei last_scanned_block - Puffer.
create table if not exists public.project_nft_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null,
  chain_key text not null,
  wallet_address text not null,
  nft_contract text,
  nft_id bigint not null,
  nft_name text,
  nft_subtype text,
  tx_hash text not null,
  block_number bigint not null,
  tx_timestamp timestamptz,
  param1 text,
  param2 text,
  reward_aptm numeric not null default 0,
  gas_aptm numeric not null default 0,
  net_aptm numeric not null default 0,
  aptm_usd numeric,
  reward_usd numeric,
  gas_usd numeric,
  price_block bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, project_key, chain_key, tx_hash)
);

create index if not exists project_nft_claims_wallet_block_idx
on public.project_nft_claims(user_id, project_key, chain_key, wallet_address, block_number);

create index if not exists project_nft_claims_nft_idx
on public.project_nft_claims(user_id, project_key, chain_key, wallet_address, nft_id, block_number);

alter table public.project_nft_claims enable row level security;

drop policy if exists project_nft_claims_select_own on public.project_nft_claims;
create policy project_nft_claims_select_own on public.project_nft_claims
for select to authenticated using (auth.uid() = user_id);

drop policy if exists project_nft_claims_insert_own on public.project_nft_claims;
create policy project_nft_claims_insert_own on public.project_nft_claims
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists project_nft_claims_update_own on public.project_nft_claims;
create policy project_nft_claims_update_own on public.project_nft_claims
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists project_nft_claims_delete_own on public.project_nft_claims;
create policy project_nft_claims_delete_own on public.project_nft_claims
for delete to authenticated using (auth.uid() = user_id);
