-- Wallet Tracking · DAO1/Apertum · zentrale Transaktionshistorie · Phase 2l
-- EINMAL nach 005-dao1-claim-cache.sql ausführen.

create table if not exists public.project_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null,
  chain_key text not null,
  wallet_address text not null,
  tx_hash text not null,
  block_number bigint,
  tx_timestamp timestamptz,
  from_address text,
  to_address text,
  direction text,
  method text,
  selector text,
  status text,
  value_aptm numeric not null default 0,
  gas_aptm numeric not null default 0,
  raw_input text,
  claim_nft_id bigint,
  claim_nft_name text,
  claim_nft_subtype text,
  claim_reward_aptm numeric,
  aptm_usd numeric,
  value_usd numeric,
  gas_usd numeric,
  claim_reward_usd numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, project_key, chain_key, wallet_address, tx_hash)
);

create index if not exists project_transactions_wallet_time_idx
on public.project_transactions(user_id, project_key, chain_key, wallet_address, tx_timestamp desc);

create index if not exists project_transactions_wallet_block_idx
on public.project_transactions(user_id, project_key, chain_key, wallet_address, block_number desc);

create index if not exists project_transactions_claim_idx
on public.project_transactions(user_id, project_key, chain_key, wallet_address, claim_nft_id)
where claim_nft_id is not null;

alter table public.project_transactions enable row level security;

drop policy if exists project_transactions_select_own on public.project_transactions;
create policy project_transactions_select_own on public.project_transactions
for select to authenticated using (auth.uid() = user_id);

drop policy if exists project_transactions_insert_own on public.project_transactions;
create policy project_transactions_insert_own on public.project_transactions
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists project_transactions_update_own on public.project_transactions;
create policy project_transactions_update_own on public.project_transactions
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists project_transactions_delete_own on public.project_transactions;
create policy project_transactions_delete_own on public.project_transactions
for delete to authenticated using (auth.uid() = user_id);

-- project_scan_state aus Migration 005 wird weiterverwendet.
-- Neuer scan_type: transactions_wallet_v1.
