-- Wallet Tracking · Phase 2ac
-- Bestandesaufnahme per 31.12 persistent speichern.
-- EINMAL in Supabase ausführen. Nicht erneut nötig, wenn Tabellen/Policies bereits bestehen.

create table if not exists public.year_end_positions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  snapshot_date date not null,
  timezone text not null default 'Europe/Zurich',
  wallet_id uuid not null,
  wallet_label text not null,
  wallet_address text,
  chain_key text not null,
  asset_key text not null,
  symbol text,
  decimals integer,
  amount numeric,
  block_ref bigint,
  price_usd numeric,
  value_usd numeric,
  balance_source text,
  price_source text,
  status text not null default 'verifiziert',
  error_message text,
  calculated_at timestamptz not null default now(),
  unique(user_id,snapshot_date,wallet_id,chain_key,asset_key)
);
create index if not exists year_end_positions_user_date_idx on public.year_end_positions(user_id,snapshot_date);
create index if not exists year_end_positions_wallet_idx on public.year_end_positions(user_id,wallet_id,snapshot_date);
alter table public.year_end_positions enable row level security;
drop policy if exists "year_end_positions_select_own" on public.year_end_positions;
create policy "year_end_positions_select_own" on public.year_end_positions for select to authenticated using (auth.uid()=user_id);
drop policy if exists "year_end_positions_insert_own" on public.year_end_positions;
create policy "year_end_positions_insert_own" on public.year_end_positions for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "year_end_positions_update_own" on public.year_end_positions;
create policy "year_end_positions_update_own" on public.year_end_positions for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "year_end_positions_delete_own" on public.year_end_positions;
create policy "year_end_positions_delete_own" on public.year_end_positions for delete to authenticated using (auth.uid()=user_id);

create table if not exists public.year_end_coverage (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  snapshot_date date not null,
  wallet_scope text not null default '__all',
  chain_key text not null,
  status text not null,
  scope text,
  detail text,
  calculated_at timestamptz not null default now(),
  unique(user_id,snapshot_date,wallet_scope,chain_key)
);
create index if not exists year_end_coverage_user_date_idx on public.year_end_coverage(user_id,snapshot_date);
alter table public.year_end_coverage enable row level security;
drop policy if exists "year_end_coverage_select_own" on public.year_end_coverage;
create policy "year_end_coverage_select_own" on public.year_end_coverage for select to authenticated using (auth.uid()=user_id);
drop policy if exists "year_end_coverage_insert_own" on public.year_end_coverage;
create policy "year_end_coverage_insert_own" on public.year_end_coverage for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "year_end_coverage_update_own" on public.year_end_coverage;
create policy "year_end_coverage_update_own" on public.year_end_coverage for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "year_end_coverage_delete_own" on public.year_end_coverage;
create policy "year_end_coverage_delete_own" on public.year_end_coverage for delete to authenticated using (auth.uid()=user_id);
