-- Wallet Tracking · generischer LP/PCLP-History-Cache · Phase 2af
-- EINMAL nach 013-anoubis-predefined-token.sql ausführen.
-- Speichert unveränderliche Add-/Remove-Liquidity-Ereignisse dauerhaft pro User/Wallet.
-- Der inkrementelle Scanstand wird in public.project_scan_state (Migration 005) geführt
-- mit scan_type = 'lp_history_v2'.

create table if not exists public.lp_history_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null,
  chain_key text not null,
  wallet_address text not null,
  pair_address text not null,
  lp_label text,
  token0_address text not null,
  token0_symbol text,
  token0_decimals integer,
  token1_address text not null,
  token1_symbol text,
  token1_decimals integer,
  tx_hash text not null,
  block_number bigint not null,
  tx_timestamp timestamptz,
  event_type text not null check (event_type in ('add','remove')),
  log_index integer not null default 0,
  lp_delta numeric not null,
  amount0 numeric not null default 0,
  amount1 numeric not null default 0,
  price0_usd numeric,
  price1_usd numeric,
  value_usd numeric,
  price_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, project_key, chain_key, wallet_address, pair_address, tx_hash, event_type)
);

create index if not exists lp_history_events_wallet_block_idx
on public.lp_history_events(user_id, project_key, chain_key, wallet_address, block_number desc);

create index if not exists lp_history_events_pair_idx
on public.lp_history_events(user_id, project_key, chain_key, pair_address, block_number desc);

alter table public.lp_history_events enable row level security;

drop policy if exists lp_history_events_select_own on public.lp_history_events;
create policy lp_history_events_select_own on public.lp_history_events
for select to authenticated using (auth.uid() = user_id);

drop policy if exists lp_history_events_insert_own on public.lp_history_events;
create policy lp_history_events_insert_own on public.lp_history_events
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists lp_history_events_update_own on public.lp_history_events;
create policy lp_history_events_update_own on public.lp_history_events
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists lp_history_events_delete_own on public.lp_history_events;
create policy lp_history_events_delete_own on public.lp_history_events
for delete to authenticated using (auth.uid() = user_id);

comment on table public.lp_history_events is
'Generischer Supabase-Cache für Add-/Remove-Liquidity-Historien (DAO1/Apertum, TLN/VOW BSC PCLP und Ethereum V2-LPs). Aktuelle LP-Bestände/Reserven bleiben live.';
