-- Wallet Tracking · LP/PCLP-Positions-Cache · Phase 2am
-- EINMAL nach 015-puglord-predefined-token.sql ausführen.
-- Speichert die beim bewussten Klick auf "Daten aktualisieren" ermittelten
-- aktuellen LP-Positionen sowie den 31.12.-Vergleichsstand. Beim Öffnen der
-- Projekt-Tabs werden danach ausschließlich Supabase-Caches gelesen.

create table if not exists public.lp_position_cache (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null,
  chain_key text not null,
  wallet_address text not null,
  pair_address text not null,
  lp_label text,
  token0_address text not null,
  token0_symbol text,
  token0_decimals integer,
  token1_address text not null,
  token1_symbol text,
  token1_decimals integer,
  current_lp numeric not null default 0,
  current_amount0 numeric not null default 0,
  current_amount1 numeric not null default 0,
  current_share numeric not null default 0,
  current_usd numeric,
  snapshot_date date,
  snapshot_lp numeric not null default 0,
  snapshot_usd numeric,
  refreshed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, project_key, chain_key, wallet_address, pair_address)
);

create index if not exists lp_position_cache_scope_idx
on public.lp_position_cache(user_id, project_key, chain_key, wallet_address);

alter table public.lp_position_cache enable row level security;

drop policy if exists lp_position_cache_select_own on public.lp_position_cache;
create policy lp_position_cache_select_own on public.lp_position_cache
for select to authenticated using (auth.uid() = user_id);

drop policy if exists lp_position_cache_insert_own on public.lp_position_cache;
create policy lp_position_cache_insert_own on public.lp_position_cache
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists lp_position_cache_update_own on public.lp_position_cache;
create policy lp_position_cache_update_own on public.lp_position_cache
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists lp_position_cache_delete_own on public.lp_position_cache;
create policy lp_position_cache_delete_own on public.lp_position_cache
for delete to authenticated using (auth.uid() = user_id);

comment on table public.lp_position_cache is
'Persistenter Cache für aktuelle und 31.12.-LP/PCLP-Positionen. Wird nur durch explizites Daten aktualisieren erneuert; Projekt-Tabs lesen beim Öffnen ausschließlich Supabase.';
