-- Wallet Tracking · TLN/VOW BSC LP-Staking · Phase 2an
-- Version: 28.08.2026, 18:39 Europe/Paris
--
-- NEU: EINMAL nach 016-lp-position-cache.sql ausführen.
-- 001–016 NICHT erneut ausführen, sofern sie bereits gelaufen sind.
--
-- Ziel:
-- - bekannte TLN/VOW-Staking-Contracts zentral konfigurieren;
-- - bestehenden lp_history_events um Stake/Unstake/Versenden/Empfangen erweitern;
-- - lp_position_cache in Wallet-LP, Staking-LP und wirtschaftlichen Gesamtbestand aufteilen.

begin;

create table if not exists public.defi_staking_contracts (
  id bigint generated by default as identity primary key,
  project_key text not null,
  chain_key text not null,
  contract_address text not null,
  label text not null,
  pair_address text,
  pair_label text,
  role text not null default 'staking',
  classify_transfers boolean not null default false,
  lock_days integer,
  notes text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_key, chain_key, contract_address)
);

create index if not exists defi_staking_contracts_lookup_idx
on public.defi_staking_contracts(project_key, chain_key, enabled, classify_transfers);

alter table public.defi_staking_contracts enable row level security;
drop policy if exists defi_staking_contracts_select_authenticated on public.defi_staking_contracts;
create policy defi_staking_contracts_select_authenticated on public.defi_staking_contracts
for select to authenticated using (enabled = true);

-- Bestehenden LP-Eventcache erweitern. Ein Transfer an einen beliebigen Smart Contract
-- ist ausdrücklich KEIN Stake. Stake/Unstake entsteht nur bei einem bestätigten Eintrag
-- in defi_staking_contracts mit classify_transfers=true.
alter table public.lp_history_events drop constraint if exists lp_history_events_event_type_check;
alter table public.lp_history_events add constraint lp_history_events_event_type_check
check (event_type in ('add','remove','send','receive','stake','unstake'));

alter table public.lp_history_events
  add column if not exists counterparty text,
  add column if not exists staking_contract text,
  add column if not exists staking_label text;

alter table public.lp_position_cache
  add column if not exists current_wallet_lp numeric not null default 0,
  add column if not exists current_staked_lp numeric not null default 0,
  add column if not exists snapshot_wallet_lp numeric not null default 0,
  add column if not exists snapshot_staked_lp numeric not null default 0;

comment on column public.lp_position_cache.current_lp is
'Wirtschaftlicher LP-Gesamtbestand: LP in Wallet + offene gestakte LP.';
comment on column public.lp_position_cache.snapshot_lp is
'Wirtschaftlicher LP-Gesamtbestand am gespeicherten Stichtag: Wallet-LP + damals offene gestakte LP.';

-- Bestätigte TLN-Webapp-/Legacy-Stakingziele. Pair-spezifische Zuordnung wird nur
-- hinterlegt, wenn sie belastbar bekannt ist. Ohne pair_address darf ein bestätigtes
-- Legacy-Ziel alle TLN/VOW-LP-Transfers an genau diesen Contract klassifizieren.
insert into public.defi_staking_contracts
(project_key,chain_key,contract_address,label,pair_address,pair_label,role,classify_transfers,notes)
values
('tln_vow','bsc','0xe3d90dcb3e13d5f7488d5c538d0255b1d294d83d','TLN Protocol Staking Reward (shared)',null,null,'controller',false,'Gemeinsamer Reward/Controller; nicht allein als LP-Stake-Ziel werten.'),
('tln_vow','bsc','0x35592ed68f69430163d5156b0e7033992a1186cd','BTCB / VOW LP Staking',null,'BTCB / VOW LP','staking',true,'Bestätigtes LP-Stakingziel.'),
('tln_vow','bsc','0x67518d0525788a34a23cf611838635a29c03b78a','VOW / v$ LP Staking',null,'VOW / v$ LP','staking',true,'Bestätigtes LP-Stakingziel.'),
('tln_vow','bsc','0xf7fd35c4a304b55284e3b76d2b84b8951f63987d','VOW / USDT LP Staking',null,'VOW / USDT LP','staking',true,'Bestätigtes LP-Stakingziel.'),
('tln_vow','bsc','0xdf9dc89d6b6d61ed0239361eba69d1c999c8cdeb','USDC / v$ LP Staking',null,'USDC / v$ LP','staking',true,'Bestätigtes LP-Stakingziel.'),
('tln_vow','bsc','0x8ab468a067983e617c37f2ee15419395caba73fb','vPound / vEuro LP Staking',null,'v£ / v€ LP','staking',true,'Bestätigtes LP-Stakingziel.'),
('tln_vow','bsc','0x2199898e1af5ff75bf5daa23fb205ac007ab7c26','vEuro / VOW LP Staking',null,'v€ / VOW LP','staking',true,'Bestätigtes LP-Stakingziel.'),
('tln_vow','bsc','0x3c0655c7d50f75addbd475d21a35e5660ad5f944','vPound / VOW LP Staking',null,'v£ / VOW LP','staking',true,'Bestätigtes LP-Stakingziel.'),
('tln_vow','bsc','0x85f82230883693f1bbff65be1f7663ee5f0aa5f8','PC LP VOW/v$ (Legacy)',null,'PC LP VOW/v$','legacy',true,'Historisches TLN-Stakingziel; Pair wird aus dem tatsächlichen LP-Transfer bestimmt.'),
('tln_vow','bsc','0x4857d369e18aba003ff6ec934cf046148df5d590','PC LP TLN+ (Legacy)',null,'PC LP TLN+','legacy',true,'Historisches TLN-Stakingziel.'),
('tln_vow','bsc','0x4a050fa27861ae2f0d63fb5da986e56ac510b201','PC LP VOW/v$ (Legacy 2)',null,'PC LP VOW/v$','legacy',true,'Historisches TLN-Stakingziel.'),
('tln_vow','bsc','0x43e457164eff66d1f975dcb9d2504ab29e36264e','Higher Value Stake (Legacy)',null,'Higher Value Stake','legacy',true,'Historisches TLN-Stakingziel; Lock-Dauer noch nicht als verifiziert hinterlegt.'),
('tln_vow','bsc','0x9a9e97a015ca65f48973835b45d4e28a99f89191','Original LPT (Legacy)',null,'Original LPT','legacy',true,'Historisches TLN-Stakingziel.')
on conflict (project_key,chain_key,contract_address) do update set
  label=excluded.label,
  pair_address=coalesce(excluded.pair_address,public.defi_staking_contracts.pair_address),
  pair_label=coalesce(excluded.pair_label,public.defi_staking_contracts.pair_label),
  role=excluded.role,
  classify_transfers=excluded.classify_transfers,
  notes=excluded.notes,
  enabled=true,
  updated_at=now();

commit;
