-- WalletTracking · TLN Wallet Identity Cache
-- Nächste Migration nach 021-predefined-token-historical-staking.sql
--
-- Zweck:
-- Persistenter Cache für bestätigte TLN-/Node-IDs von beliebigen Wallets,
-- insbesondere fremden Staker-Wallets aus Referral-Rewards.
-- Die bestehende public.wallets-Tabelle wird bewusst NICHT erweitert, weil
-- Referral-Staker nicht zwingend Wallets des eingeloggten Users sind.
--
-- WICHTIG:
-- Es werden nur bestätigte IDs gespeichert. "unresolved" gehört nicht in diese Tabelle.

begin;

create table if not exists public.tln_wallet_identity_cache (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null default 'tln_vow',
  chain_key text not null default 'bsc',
  wallet_address text not null,
  node_id bigint,
  referred_by_id bigint,
  source text not null,
  source_contract text,
  source_method text,
  verified_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, project_key, chain_key, wallet_address),
  constraint tln_wallet_identity_cache_has_identity_chk
    check (node_id is not null or referred_by_id is not null),
  constraint tln_wallet_identity_cache_node_id_chk
    check (node_id is null or node_id > 0),
  constraint tln_wallet_identity_cache_referred_by_id_chk
    check (referred_by_id is null or referred_by_id > 0)
);

create index if not exists tln_wallet_identity_cache_wallet_idx
on public.tln_wallet_identity_cache(user_id, project_key, chain_key, wallet_address);

alter table public.tln_wallet_identity_cache enable row level security;

drop policy if exists tln_wallet_identity_cache_select_own
on public.tln_wallet_identity_cache;
create policy tln_wallet_identity_cache_select_own
on public.tln_wallet_identity_cache
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists tln_wallet_identity_cache_insert_own
on public.tln_wallet_identity_cache;
create policy tln_wallet_identity_cache_insert_own
on public.tln_wallet_identity_cache
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists tln_wallet_identity_cache_update_own
on public.tln_wallet_identity_cache;
create policy tln_wallet_identity_cache_update_own
on public.tln_wallet_identity_cache
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists tln_wallet_identity_cache_delete_own
on public.tln_wallet_identity_cache;
create policy tln_wallet_identity_cache_delete_own
on public.tln_wallet_identity_cache
for delete to authenticated
using (auth.uid() = user_id);

comment on table public.tln_wallet_identity_cache is
'User-spezifischer persistenter Cache für bestätigte TLN-/Node-ID-Zuordnungen beliebiger Wallets. Referral-Staker müssen nicht in public.wallets vorhanden sein.';

commit;

-- Kontrolle nach Ausführung:
-- select user_id, wallet_address, node_id, referred_by_id, source,
--        source_contract, source_method, verified_at
-- from public.tln_wallet_identity_cache
-- order by updated_at desc;
