-- WalletTracking
-- 049-dao1-transaction-asset-flows.sql
-- DAO1/Apertum: assetgenaue ERC-20-Flows für Claims, Referral Rewards und Transaktionshistorie.
--
-- AUSFÜHRUNG:
--   Dieses Script KOMPLETT AUF EINMAL ausführen.
--   Es enthält mehrere DDL/DML-Statements in EINER Transaktion.
--   Am Ende gibt es GENAU EIN Resultset zur Kontrolle.
--   Reihenfolge: nach 048-dao1-apertum-price-anchors.sql.

begin;

create table if not exists public.project_transaction_asset_flows (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_key text not null,
  chain_key text not null,
  wallet_id uuid not null,
  flow_key text not null,
  tx_hash text not null,
  block_number bigint not null,
  tx_timestamp timestamptz,
  log_index integer not null default -1,
  token_address text not null,
  token_symbol text,
  token_name text,
  token_decimals integer not null default 18,
  amount_raw text not null default '0',
  amount numeric not null default 0,
  counterparty_address text,
  direction text not null,
  price_usd numeric,
  value_usd numeric,
  price_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, project_key, chain_key, wallet_id, flow_key)
);

create index if not exists project_transaction_asset_flows_wallet_block_idx
  on public.project_transaction_asset_flows(user_id, project_key, chain_key, wallet_id, block_number desc);

create index if not exists project_transaction_asset_flows_tx_idx
  on public.project_transaction_asset_flows(user_id, project_key, chain_key, wallet_id, tx_hash);

create index if not exists project_transaction_asset_flows_token_idx
  on public.project_transaction_asset_flows(user_id, project_key, chain_key, wallet_id, token_address, block_number desc);

alter table public.project_transaction_asset_flows enable row level security;

drop policy if exists project_transaction_asset_flows_select_own on public.project_transaction_asset_flows;
create policy project_transaction_asset_flows_select_own
  on public.project_transaction_asset_flows
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists project_transaction_asset_flows_insert_own on public.project_transaction_asset_flows;
create policy project_transaction_asset_flows_insert_own
  on public.project_transaction_asset_flows
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists project_transaction_asset_flows_update_own on public.project_transaction_asset_flows;
create policy project_transaction_asset_flows_update_own
  on public.project_transaction_asset_flows
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists project_transaction_asset_flows_delete_own on public.project_transaction_asset_flows;
create policy project_transaction_asset_flows_delete_own
  on public.project_transaction_asset_flows
  for delete to authenticated
  using (auth.uid() = user_id);

-- Generische Claim-Auszahlung: reward_aptm bleibt als Legacy-Feld erhalten,
-- ist aber bei wUSDT/anderen Tokens nicht mehr die fachliche Quelle.
alter table public.project_nft_claims
  add column if not exists reward_asset_address text,
  add column if not exists reward_asset_symbol text,
  add column if not exists reward_asset_decimals integer,
  add column if not exists reward_asset_amount numeric,
  add column if not exists reward_asset_usd numeric,
  add column if not exists reward_asset_price_source text;

-- Bei nicht-APTM-Claims darf reward_aptm NULL sein.
alter table public.project_nft_claims
  alter column reward_aptm drop not null;

commit;

-- Genau EIN Resultset:
select
  'project_transaction_asset_flows'::text as table_name,
  (select count(*) from information_schema.columns
    where table_schema='public' and table_name='project_transaction_asset_flows') as column_count,
  exists(
    select 1 from information_schema.columns
    where table_schema='public' and table_name='project_nft_claims' and column_name='reward_asset_symbol'
  ) as claim_asset_columns_ready;
